opendebate.processTimeline({
  "iface": "timeline", 
  "entries": [
    {
      "category": "robots", 
      "city": "Great Neck", 
      "votes": 0, 
      "last_name": "Jucovy", 
      "user_id": 1195198, 
      "submission": "Are you a robot?", 
      "district": "NY_03", 
      "created": "2013-08-20T13:16:03", 
      "state_votes": 0, 
      "first_name": "Ethan", 
      "district_votes": 0, 
      "state": "NY", 
      "iface": "timeline_question", 
      "y": 40.7867, 
      "x": -73.7258, 
      "latest_vote": null, 
      "id": 16320118
    }, 
    {
      "category": "robots", 
      "city": "Great Neck", 
      "votes": 0, 
      "last_name": "Jucovy", 
      "user_id": 1195198, 
      "submission": "Do you believe that robots can love?  If so, do you believe that they should?", 
      "district": "NY_03", 
      "created": "2013-08-20T02:35:57", 
      "state_votes": 0, 
      "first_name": "Ethan", 
      "district_votes": 0, 
      "state": "NY", 
      "iface": "timeline_question", 
      "y": 40.7867, 
      "x": -73.7258, 
      "latest_vote": null, 
      "id": 16319927
    }, 
    {
      "category": "_other", 
      "city": "Great Neck", 
      "votes": 0, 
      "last_name": "Jucovy", 
      "user_id": 1195198, 
      "submission": "This is a robot's question, that focuses on a robot's concerns.", 
      "district": "NY_03", 
      "created": "2013-08-20T02:35:04", 
      "state_votes": 0, 
      "first_name": "Ethan", 
      "district_votes": 0, 
      "state": "NY", 
      "iface": "timeline_question", 
      "y": 40.7867, 
      "x": -73.7258, 
      "latest_vote": null, 
      "id": 16319926
    }
  ]
});
